```{r}
library(datasets)
```


```{r}
head(iris)
```

```{r}
plot(iris$Species) # Categorical variable
```
```{r}
plot(iris$Petal.Length) #Quantitative variable
```


```{r}
plot(iris$Species,iris$Petal.Width) #Categorical X Quantitative
```


```{r}
plot(iris$Petal.Length,iris$Petal.Width) #Quantitative Pair
```


```{r}
plot(iris)
```


```{r}
plot(iris$Petal.Length,iris$Petal.Width,
     col="blue",
     pch=24,
     bg="red",
     cex=2,
     main="Iris: Petal Length vs. Petal Width",
     xlab="Petal Length",
     ylab = "Petal Width"
     )

# Other pch values
# pch = 0,square
# pch = 1,circle
# pch = 2,triangle point up
# pch = 3,plus
# pch = 4,cross
# pch = 5,diamond
# pch = 6,triangle point down
# pch = 7,square cross
# pch = 8,star
# pch = 9,diamond plus
# pch = 10,circle plus
# pch = 11,triangles up and down
# pch = 12,square plus
# pch = 13,circle cross
# pch = 14,square and triangle down
# pch = 15, filled square
# pch = 16, filled circle
# pch = 17, filled triangle point-up
# pch = 18, filled diamond
# pch = 19, solid circle
# pch = 20,bullet (smaller circle)
# pch = 21, filled circle blue
# pch = 22, filled square blue
# pch = 23, filled diamond blue
# pch = 24, filled triangle point-up blue
# pch = 25, filled triangle point down blue
```
```{r}
# Plot Formulas with plot()
plot(cos,0,2*pi)
plot(exp,1,5)
```
```{r}
plot(dnorm,-3,+3,
     col="#cc0000",
     lwd=5, #line width
     main="Standard Normal Distribution",
     xlab="Z-Scores",
     ylab="Density")
```



Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.



